Customer service
Cactusmachete/NucleusProject pull request #6
Opened 2020-12-12 09:00 UTC by Rishabhdhiman09

2020-12-12 09:19 UTC, Cactusmachete requested changes
looks good, just a few minor changes needed

2020-12-12 09:19 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/newCustomerService.css
> +}
can you rename the file to be something like customerServiceHome.css?

2020-12-12 09:19 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/newCustomerService.html
> +<!DOCTYPE html>
this file could be renamed as well, I think.

2020-12-12 09:19 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/newCustomerService.html
> +                <div class="social-part">
this div can be deleted, I think. It's all hidden anyways.

2020-12-12 09:19 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/newCustomerService.html
> +                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
for this dropdown's id, and the rest, why not follow something along the lines of "navbardrop1", "navbardrop2", etc?

2020-12-12 10:14 UTC, Cactusmachete requested changes
just delete the extra file and div, and rename the navbar dowpdowns, and it should all be good

2020-12-12 10:14 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/customerServiceHome.css.css
> +  border: 1px solid #E8E8E8;
why are there two css files?

2020-12-12 10:14 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/customerServiceHome.html
> +                <div class="social-part">
this div should be deleted.

2020-12-12 10:14 UTC, Cactusmachete commented on src/main/webapp/WEB-INF/views/customerServiceHome.html
> +                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
navbar dropdown ids still need changing, I think

2020-12-13 06:30 UTC, Rishabhdhiman09 commented on src/main/webapp/WEB-INF/views/customerServiceHome.css.css
> +  border: 1px solid #E8E8E8;
Extra file deleted

2020-12-13 07:25 UTC, merged